### ISSUE TITLE
Parameter "client_id" is missing or does not match any client, or secret is invalid

### ISSUE THREAD

**Issue by adamrandazzo** [akeneo/transporteo#103]
I upgraded to alpha3 today as it resolved previous bugs that I was experiencing. I was able to get a little further in the process, but received the following error during the `Migrating Products Data` step:

```
  [Akeneo\Pim\Exception\UnprocessableEntityHttpException]
  Parameter "client_id" is missing or does not match any client, or secret is invalid
```
I generated a brand new client_id from my source PIM immediately before this to ensure that it was valid and correct.

```
php app/console pim:oauth-server:create-client \
     --grant_type="password" \
     --grant_type="refresh_token" \
     --env=prod \
     --label=“Transporteo”
```

Any help would be appreciated

**Comment by adamrandazzo** [comment]
Some additional information:

I performed some troubleshooting with Alexandre Hocquard via the Slack #web-api channel. I updated my apache config and was able to get a key via CURL, but still not via Transporteo. (https://www.akeneo.com/forums/topic/code-422-when-trying-to-get-a-token-ce-1-7/)

**Comment by LaurentPetard** [comment]
Hello @adamrandazzo 

We're investigating this weird problem. 

What's certain is that it's not in Transporteo itself. The API authentication (including the base 64 encoding) is fully handled by  https://github.com/akeneo/php-api-client

Best regards,
Laurent

**Comment by adamrandazzo** [comment]
Thank you @LaurentPetard - I will attempt to use the API client in isolation to see if I can figure anything out.

**Comment by adamrandazzo** [comment]
I was able to use the API client in isolation. I ended up deleting the contents of the var/ directory and it now worked. I am going to close this issue.

**Comment by akosglue** [comment]
deleting the contents of the var/ directory didn't help me with this issue.

**Comment by Immortal1900** [comment]
Can anyone tell why do we see this error? I removed caches from php-symphony since then I'm getting this error, I'm not sure what are we checking in the caches?
