### ISSUE TITLE
Reorganize code to make it more clear

### ISSUE THREAD

**Issue by jjanvier** [akeneo/transporteo#41]
## Questions

- what is `Akeneo\PimMigration\Domain\PimDetection`? weird to have that with only one class inside
- maybe rename `EnterpriseEditionAccessVerification` to `AccessVerification`
- would be cool if migration steps match the naming of the diagram
- no migration step GuessDestinationPimLocation? DestinationPimDetection? DestinationPimCheckRequirements?
- PimConfiguration folder is a little bit weird all alone; also need to rewrite all phpdoc

- should we include a folder like `1dot7to2` or `NameOf1.7ToNameOf2.0`? maybe later?

**Comment by anaelChardan** [comment]
Done !
