### ISSUE TITLE
Add support for SSH keys with a passphrase

### ISSUE THREAD

**Issue by gplanchat** [akeneo/transporteo#66]
Using a SSH key with a passphrase does not succeed, after inputting the connection information the script crashes telling us the connection is impossible.

`Impossible to connect to ubuntu@...cloudapp.azure.com:22 using this ssh key : /Users/gplanchat/.ssh/id_rsa`

**Comment by anaelChardan** [comment]
Hi @gplanchat, thanks for raising this issue! 

Indeed it is something not supported yet, but we will have a look on it as it can be a common case.

Thanks :-).

Anaël.

**Comment by LaurentPetard** [comment]
Done in 1.0.0-alpha3

**Comment by gplanchat** [comment]
![](https://media.giphy.com/media/YTbZzCkRQCEJa/giphy.gif)
