### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot unpack array with string keys

### ISSUE THREAD

**Issue by LaureBro** [akeneo/transporteo#89]
Error while using the bundle:
PHP Fatal error:  Uncaught Error: Cannot unpack array with string keys in /home/akeneo/transporteo/vendor/php-ds/php-ds/src/Traits/Sequence.php:31
Stack trace:
#0 /home/akeneo/transporteo/src/Domain/Pim/ComposerJson.php(32): Ds\Vector->__construct(Array)
#1 /home/akeneo/transporteo/src/Domain/Pim/SourcePim.php(111): Akeneo\PimMigration\Domain\Pim\ComposerJson->getRepositories()
#2 /home/akeneo/transporteo/src/Infrastructure/MigrationStep/S020FromSourcePimApiConfiguredToSourcePimDetected.php(40): Akeneo\PimMigration\Domain\Pim\SourcePim::fromSourcePimConfiguration(Object(Akeneo\PimMigration\Infrastructure\Pim\SshConnection), '/home/akeneo/pi...', Object(Akeneo\PimMigration\Domain\Pim\PimConfiguration), Object(Akeneo\PimMigration\Domain\Pim\PimApiParameters))
#3 [internal function]: Akeneo\PimMigration\Infrastructure\MigrationStep\S020FromSourcePimApiConfiguredToSourcePimDetected->onSourcePimDetection(Object(Symfony\Component\Workflow\Event\Event), 'workflow.transp...', Object(Symfony\Component\EventDispatcher\ContainerAwareEven in /home/akeneo/transporteo/vendor/php-ds/php-ds/src/Traits/Sequence.php on line 31

Issue seems to come from /home/akeneo/transporteo/vendor/php-ds/php-ds/src/Traits/Sequence.php:31(: innerVariation :)

(come to me if you need more info!)

Thanks!

**Comment by LaurentPetard** [comment]
When InnerVariationBundle is installed according the doc, the command `composer config repositories.innerVariation '{"type": "vcs", "url": "ssh://git@distribution.akeneo.com:443/InnerVariationBundle", "branch": "master"}'
`
will update the composer.json to add the repository as follow : 

`"repositories": {
        "0": {
            "type": "vcs",
            "url": "https://github.com/akeneo/pim-community-dev.git",
            "branch": "master"
        },
        "innerVariation": {
            "type": "vcs",
            "url": "https://github.com/akeneo/InnerVariationBundle.git",
            "branch": "master"
        }
    },`

When the file composer.json is loaded in `Domain/Pim/AbstractPimConfigurator.php` it use a class `Ds\Vector` for the repositories, which is not suited for a associated array. 

We have to use another Ds class, or if the Composer repositories are not used, to remove this property from the class `Akeneo\PimMigration\Domain\Pim\ComposerJson`

**Comment by LaurentPetard** [comment]
fixed in 1.0.0-alpha3
